zuul:
  routes:
    module-users:
      path: /users/**
      serviceId: module-users
      stripPrefix: false
      
security:
  oauth2:
    resource:
      
      userInfoUri: https://localhost:9999/auth/user
      
eureka:  
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: false
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
