spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_oauth 
    username: root
    password: root 

eureka:  
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: false
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
app:
  resource-id: app-tool
  client: app-tool
  client-remember-me: app-tool-remember-me
  scope: app-tool
  access-token-validity: 600
  refresh-token-validity: 1800
  signing-key: app-tool-secret
  
